print("----------------------------------------------------------------")
print("                Rasberry Shop VAT INVOICE")
print("----------------------------------------------------------------")
print("Blueberry x 1                       : 3,000,000 THB")
print("Ipad pro m2 x 1                     : 23,700 THB")
print("Nintendo Switch x 2                 : 24,800 THB")
print("PS5 Controller x 3                  : 4,200 THB")
print("UNI 0.5 MIX Nano Dia Color x 1      : 65 THB")
print("ควอนตัม จากแมวพิศวงสู่ควอนตัมคอมพิวเตอร์ x 1 : 359 THB")
print("Logitech G-Pro gaming x Headset x 1 : 3,690 THB")
print("Iphone 12 128GB x 1 : 27,900 THB")
print("----------------------------------------------------------------")
print("Total                               : ขี้เกียจคิดเลขครับผมตั้งราคามั่ว")
